# Generated by Django 4.2.6 on 2024-01-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pagina_noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, unique=True, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('apodo', models.TextField(unique=True, verbose_name='Nombre usuario')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('foto_perfil', models.ImageField(upload_to='', verbose_name='Foto de Perfil')),
                ('follow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguido', to='main.usuario', verbose_name='Seguido')),
                ('follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguidor', to='main.usuario', verbose_name='Seguidor')),
            ],
        ),
        migrations.CreateModel(
            name='noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True)),
                ('genero_musical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genero')),
                ('idPagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pagina_noticia')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField()),
                ('generos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
                ('oyentes_mensuales', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='')),
                ('canciones', models.ManyToManyField(to='main.cancion')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True)),
                ('duracionTotal', models.IntegerField()),
                ('canciones', models.ManyToManyField(to='main.cancion')),
            ],
        ),
    ]
