# Generated by Django 4.2.6 on 2024-02-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='oyentes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
    ]
