# Generated by Django 4.2.6 on 2024-02-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cancion_oyentes_alter_cancion_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='nombre',
            field=models.TextField(default='Patata', unique=True, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
