# Generated by Django 4.2.6 on 2024-02-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cancion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='generos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.genero'),
        ),
    ]
