# Generated by Django 4.2.6 on 2024-02-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cancion_generos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='generos',
        ),
        migrations.AddField(
            model_name='cancion',
            name='generos',
            field=models.ManyToManyField(to='main.genero'),
        ),
    ]
