# Generated by Django 4.2.6 on 2024-02-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_cancion_generos_cancion_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='foto',
            field=models.ImageField(default='', upload_to='', verbose_name='Foto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='generos',
            field=models.ManyToManyField(to='main.genero'),
        ),
    ]
