# Generated by Django 4.2.6 on 2024-02-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_album_foto_album_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='años_activo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
