# Generated by Django 4.2.6 on 2024-02-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_artista_años_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='foto',
        ),
    ]
