# Generated by Django 4.2.6 on 2024-03-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_artista_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='descripcion',
        ),
    ]
