# Generated by Django 4.2.6 on 2024-03-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_artista_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='link_spotify',
            field=models.URLField(default='no existe url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancion',
            name='link_youtube',
            field=models.URLField(default='no existe url'),
            preserve_default=False,
        ),
    ]
