# Generated by Django 4.2.6 on 2024-03-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cancion_link_spotify_cancion_link_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='duracion',
            field=models.DurationField(verbose_name='Duración'),
        ),
    ]
