# Generated by Django 4.2.6 on 2024-03-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_cancion_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='generos',
            field=models.ManyToManyField(to='main.genero'),
        ),
    ]
