# Generated by Django 4.2.6 on 2024-03-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_artista_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.TextField(default=1234, verbose_name='Contraseña'),
            preserve_default=False,
        ),
    ]
