# Generated by Django 4.2.6 on 2024-03-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_usuario_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
    ]
