# Generated by Django 4.2.6 on 2024-03-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_genero_color_alter_usuario_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='imagen_album',
            field=models.ImageField(blank=True, null=True, upload_to='albums/'),
        ),
    ]
