# Generated by Django 4.2.6 on 2024-03-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_album_imagen_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='imagen_album',
        ),
        migrations.AddField(
            model_name='artista',
            name='imagen_album',
            field=models.ImageField(blank=True, null=True, upload_to='albums/'),
        ),
    ]
