# Generated by Django 4.2.6 on 2024-03-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_cancion_letra'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='albums',
            field=models.ManyToManyField(to='main.album'),
        ),
    ]
