# Generated by Django 4.2.6 on 2024-04-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_artista_albums'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('followers', models.ManyToManyField(to='main.usuario')),
                ('generos', models.ManyToManyField(to='main.genero')),
            ],
        ),
        migrations.CreateModel(
            name='ListaReproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('canciones', models.ManyToManyField(blank=True, to='main.cancion', verbose_name='Canciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_reproduccion', to='main.usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='nombre',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='noticia',
        ),
        migrations.DeleteModel(
            name='pagina_noticia',
        ),
    ]
