# Generated by Django 4.2.6 on 2024-04-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_comunidad_listareproduccion_alter_album_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='follower',
        ),
        migrations.AddField(
            model_name='usuario',
            name='followers',
            field=models.ManyToManyField(related_name='follower', to='main.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='follows',
            field=models.ManyToManyField(related_name='follow', to='main.usuario'),
        ),
    ]
