# Generated by Django 4.2.6 on 2024-04-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_usuario_followers_alter_usuario_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='listareproduccion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='lista_reproducciones'),
        ),
        migrations.AlterField(
            model_name='album',
            name='foto',
            field=models.ImageField(upload_to='albums', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='imagen_album',
            field=models.ImageField(blank=True, null=True, upload_to='albums'),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='comunidades'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios', verbose_name='Foto de Perfil'),
        ),
    ]
