# Generated by Django 4.2.6 on 2024-04-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='main.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil', verbose_name='Foto de Perfil'),
        ),
    ]
