# Generated by Django 4.2.6 on 2024-05-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_artista_canciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='artistas_seguidos',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to='main.artista'),
        ),
    ]
