# Generated by Django 4.2.6 on 2024-06-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_usuario_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='imagen_album',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='letra',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='comunidad',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
